
const ABSOLUTE_POSITION_ATTRIBUTE = 'APosition';
const ABSOLUTE_POSITION_QUERY_SELECTOR = `[${ABSOLUTE_POSITION_ATTRIBUTE}]`

const ABSOLUTE_POSITION_DOM_LOAD = 'load';
//code assigns
const  ABSOLUTE_POSITION_START_CHAR = '$';
const  ABSOLUTE_POSITION_MEASURE_DIVIDER = ',';
const ABSOLUTE_POSITION_LEFT_PARENTESIS = '(';
const ABSOLUTE_POSITION_RIGHT_PARENTESIS = ')';
const  ABSOLUTE_POSITION_EMPTY_STRING = ''
const ABSOLUTE_POSITION_SPACE = ' '

const  ABSOLUTE_POSITION_VALID_NUMS = ['.','0','1','2','3','4','5','6','7','8','9'];

const ABSOLUTE_POSITION_ASPECT_RATION_SEPARATOR = ':'
//directions
const ABSOLUTE_POSITION_LEFT = 'left';
const ABSOLUTE_POSITION_TOP = 'top';
const ABSOLUTE_POSITION_WIDTH = 'width';
const ABSOLUTE_POSITION_HEIGHT = 'height';


//operators
const ABSOLUTE_POSITION_OPERATOR_PLUS = '+';
const ABSOLUTE_POSITION_OPERATOR_MIN = '-';
const ABSOLUTE_POSITION_VALID_OPERATORS = [ABSOLUTE_POSITION_OPERATOR_PLUS,ABSOLUTE_POSITION_OPERATOR_MIN]

const ABSOLUTE_POSITION_HORIZONTAL_DIRECTIONS = [ABSOLUTE_POSITION_LEFT,ABSOLUTE_POSITION_WIDTH];
const ABSOLUTE_POSITION_VERTICAL_DIRECTIONS = [ABSOLUTE_POSITION_TOP,ABSOLUTE_POSITION_HEIGHT];

//measures
const ABSOLUTE_POSITION_VIEW_WIDTH = 'vw';
const ABSOLUTE_POSITION_VIEW_HEIGHT  = 'vh';
const ABSOLUTE_POSITION_PX = 'px';
const ABSOLUTE_POSITION_PERCENT = '%';

//html tags
const ABSOLUTE_POSITION_RESIZE = 'resize';
const ABSOLUTE_POSITION_ABSOLUTE = 'absolute';


//errors
const PARENTESIS_NOT_PROVIDED = ' char:"(" not provided at:';