
const ABSOLUTE_POSITION_ATTRIBUTE = 'APosition';
const ABSOLUTE_POSITION_QUERY_SELECTOR = `[${ABSOLUTE_POSITION_ATTRIBUTE}]`


//directions
const ABSOLUTE_POSITION_LEFT = 'left';
const ABSOLUTE_POSITION_TOP = 'top';
const ABSOLUTE_POSITION_WIDTH = 'width';
const ABSOLUTE_POSITION_HEIGHT = 'height';

//operators
const ABSOLUTE_POSITION_OPERATOR_PLUS = '+';
const ABSOLUTE_POSITION_OPERATOR_MIN = '-';

const HORIZONTAL_DIRECTIONS = [ABSOLUTE_POSITION_LEFT,ABSOLUTE_POSITION_WIDTH];
const VERTICAL_DIRECTIONS = [ABSOLUTE_POSITION_TOP,ABSOLUTE_POSITION_VIEW_HEIGHT];

//measures
const ABSOLUTE_POSITION_VIEW_WIDTH = 'vw';
const ABSOLUTE_POSITION_VIEW_HEIGHT  = 'vh';
const ABSOLUTE_POSITION_PX = 'px';
const ABSOLUTE_POSITION_PERCENT = '%';

//html tags
const ABSOLUTE_POSITION_RESIZE = 'resize';
const ABSOLUTE_POSITION_ABSOLUTE = 'absolute';
